name: multimodal
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.9.6
  - cudatoolkit=11.1
  - pytorch=1.9.1
  - torchvision=0.10.1
  - pip:
    - -r requirements.txt
